### ISSUE TITLE
Small typo in documentation

### ISSUE THREAD

**Issue by carlganz** [AliciaSchep/iheatmapr#1]
Hello,

I believe in your Roxygen documentation you are missing a `@examples` here: https://github.com/AliciaSchep/iheatmapr/blob/master/R/subplot.R#L39

The example for `add_subplot` isn't appearing as a result. 

Kind Regards

**Comment by AliciaSchep** [comment]
Thanks!  Have updated the roxygen documentation & recreated the rd file.
