### ISSUE TITLE
Error when plotting covariate number exceed available discrete palettes

### ISSUE THREAD

**Issue by srsankhe** [AliciaSchep/iheatmapr#110]
`iheatmapr:::choose_discrete_palette` error's out when plotting more than 7 covariates | when number of covariates plotted exceed the available palettes. 

```
vapply(tmp2[which(tmp2 %in% tmp1)], function(x) which(tmp1 == x), "")
```
![Screenshot 2024-09-09 at 11 05 55 AM](https://github.com/user-attachments/assets/48faf492-fcc3-404b-998f-0c72b2726389)

**Comment by alanocallaghan** [comment]
Can you post a reprex? Doesn't error for me

```r
library(iheatmapr)
mat <- matrix(rnorm(100), ncol = 10, nrow = 10)
row_groups <- letters[1:10]
iheatmap(mat) %>% add_row_groups(row_groups, name = "My groups")
```

**Comment by srsankhe** [comment]
Going to close this, while trying to generate a reprex this worked as expected. I am guessing something fishy with the data, not sure if any clustering or other modifications make this pop-up. Will do some more digging around

**Comment by alanocallaghan** [comment]
Thanks, yeah the code doesn't look right but equally I couldn't get it to break, so confused. Will watch for this for sure
