### ISSUE TITLE
iheatmapr no longer produces a working plotly plot

### ISSUE THREAD

**Issue by Alanocallaghan** [AliciaSchep/iheatmapr#6]
The yaml file specifying plotly's htmlwidget dependencies is empty in recent versions (https://github.com/ropensci/plotly/commit/183006c319e37d4eed6b27abc1bdc84e5d5c990e). This code in `as_plotly()` should fix it (note `plotly:::plotlyMainBundle()`... it might be worthwhile asking Carson to export that, or some way of producing the plots manually. 

I'm submitting a PR but feel free to check it over and/or ask the ropensci team first.

    createWidget(name = "plotly",
                 x = out,
                 width = out$layout$width,
                 height = out$layout$height,
                 sizingPolicy = sizingPolicy(browser.fill = TRUE,
                                             defaultWidth = "100%",
                                             defaultHeight = 400),
                 dependencies = plotly:::plotlyMainBundle(),
                 preRenderHook = plotly_build)

**Comment by AliciaSchep** [comment]
Closed, for more discussion, see #7 and #9.  Thanks again for bringing up this issue!

**Comment by Alanocallaghan** [comment]
Makes more sense than relying on plotlys internals, it was simply the path of least resistance for me. Cheers!

On 5 Jun 2017 12:08 am, Alicia Schep <notifications@github.com> wrote:

Closed, for more discussion, see #7<https://github.com/AliciaSchep/iheatmapr/pull/7> and #9<https://github.com/AliciaSchep/iheatmapr/issues/9>. Thanks again for bringing up this issue!
